color_black="#191919"
color_red="#DE6E7C"
color_green="#819B69"
color_yellow="#B77E64"
color_blue="#6099C0"
color_magenta="#B279A7"
color_cyan="#66A5AD"
color_white="#BBBBBB"

color_bright_black="#3D3839"
color_bright_red="#E8838F"
color_bright_green="#8BAE68"
color_bright_yellow="#D68C67"
color_bright_blue="#61ABDA"
color_bright_magenta="#CF86C1"
color_bright_cyan="#65B8C1"
color_bright_white="#8E8E8E"

# status
set -g status "on"
set -g status-position "top"
set -g status-bg $color_black
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

# messages
set -g message-style "fg=$color_white,bg=$color_bright_black,align=centre"
set -g message-command-style "fg=$color_white,bg=$color_bright_black,align=centre"

# panes
set -g pane-border-style fg=$color_bright_black
set -g pane-active-border-style fg=$color_bright_white

# windows
setw -g window-status-activity-style fg=$color_bright_white,bg=$color_bright_black,none
setw -g window-status-separator ""
setw -g window-status-style fg=$color_bright_white,bg=$color_bright_black,none

# statusline
# set -g status-left "#[fg=#$color_black,bg=#$color_white] #S "
set -g status-left "#[fg=#$color_black,bg=#$color_yellow] #S "
# set -g status-left "#{?client_prefix,#[fg=#$color_black#,bg=#$color_white],#[fg=#$color_black#,bg=#$color_yellow]} #S "

# set -g status-right "#[fg=#$color_bright_white,bg=#$color_black] #{client_user}@#h "
set -g status-right "#[fg=#$color_bright_white,bg=#$color_black] #h "

# window-status
# setw -g window-status-format "#[bg=#$color_black,fg=#$color_bright_white] #I:#W#F "
# setw -g window-status-current-format "#[bg=#$color_black,fg=#$color_white] #I:#W#F "
setw -g window-status-format "#[bg=#$color_black,fg=#$color_bright_white] #I:#W "
setw -g window-status-current-format "#[bg=#$color_black,fg=#$color_yellow] #I:#W "

